name: Deploy Admin panel

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Create .env file
      run: echo "SERVER_HOST_URL=${{ secrets.SERVER_HOST_URL }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env

    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile # Adjust if Dockerfile is in the root directory
        push: true
        tags: reportal/admin-panel-frontend #Replace with your Docker Hub username and repository


    - name: Publish image to docker hub
      run: docker push reportal/admin-panel-frontend:latest

    - name: Verify Pushed Image
      run: docker pull reportal/admin-panel-frontend:latest

  # deploy:
  #   needs: build
  #   runs-on: self-hosted
  #   steps:
  #   - name: Pull image from docker hub
  #     run: docker pull reportal/admin-panel-frontend:latest

  #   - name: Delete old container
  #     run: docker rm -f admin-panel-frontend-container || true

  #   - name: Run docker container
  #     run: docker run -d -p 3000:3000 --name admin-panel-frontend-container reportal/admin-panel-frontend
